package output

import java.io.PrintWriter

import api.dtos.DSLDTO

import scala.concurrent.{ ExecutionContext, Future }

class ObjectGenerator(dsl: DSLDTO) extends CodeGenerator {

  implicit val exec: ExecutionContext = ExecutionContext.global

  def generate(outputPath: String, objectName: String): Future[Unit] = {

    val transformationsParser = dsl.transformations.map { transformation =>

      val lambda = transformation.predicate match {
        case Some(p) => "(" + p + ")"
        case None => ""
      }
      transformation.transformationName.transformationName + lambda
    }

    val res = transformationsParser.foldLeft("")(_ + "." + _)

    val inType = dsl.inType.`type`.getOrElse("")
    val outType = dsl.outType.`type`.getOrElse("")

    Future(new PrintWriter(outputPath + "\\" + objectName + ".scala") {

      write("//This file is auto generated by code")
      write(
        s"""
         |
         |object $objectName{
         |def run(data:$inType): $outType = {
         |data$res
         |}
         |
         |def main(args: Array[String]): Unit = {
         |println(run _)
         |}
         |}
    """.stripMargin)
      close()
    })
  }
}

