//This file is auto generated by code

object POC {
  def run: Int = {
    List(1, 3, 4, 2, 5, 7, 2, 123, 654, 3, 35, 312, 64, 76, 9).filter(p => p > 5).size
  }

  def main(args: Array[String]): Unit = {
    println(run)
  }
}
